// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Static-import registry of every action file. Bundlers (Nitro, Rolldown)
// see these imports and include the action modules in the server bundle.
// The agent-chat plugin normalizes each module into an ActionEntry shape.
import * as a_add_breakpoint from "../actions/add-breakpoint";
import * as a_add_fusion_screens from "../actions/add-fusion-screens";
import * as a_add_localhost_screens from "../actions/add-localhost-screens";
import * as a_analyze_brand_assets from "../actions/analyze-brand-assets";
import * as a_apply_a11y_fix from "../actions/apply-a11y-fix";
import * as a_apply_component_prop_edit from "../actions/apply-component-prop-edit";
import * as a_apply_design_state from "../actions/apply-design-state";
import * as a_apply_design_token_edit from "../actions/apply-design-token-edit";
import * as a_apply_fusion_edits from "../actions/apply-fusion-edits";
import * as a_apply_motion_edit from "../actions/apply-motion-edit";
import * as a_apply_shader_fill from "../actions/apply-shader-fill";
import * as a_apply_shader from "../actions/apply-shader";
import * as a_apply_source_edit from "../actions/apply-source-edit";
import * as a_apply_tweaks from "../actions/apply-tweaks";
import * as a_apply_visual_edit from "../actions/apply-visual-edit";
import * as a_begin_node_rewrite_request from "../actions/begin-node-rewrite-request";
import * as a_cancel_node_rewrite_request from "../actions/cancel-node-rewrite-request";
import * as a_capture_design_state from "../actions/capture-design-state";
import * as a_clone_creative_context_design_native from "../actions/clone-creative-context-design-native";
import * as a_clone_creative_context_design from "../actions/clone-creative-context-design";
import * as a_connect_assets_mcp from "../actions/connect-assets-mcp";
import * as a_connect_builder_app from "../actions/connect-builder-app";
import * as a_connect_localhost from "../actions/connect-localhost";
import * as a_create_component from "../actions/create-component";
import * as a_create_design_branch from "../actions/create-design-branch";
import * as a_create_design_from_template from "../actions/create-design-from-template";
import * as a_create_design_state from "../actions/create-design-state";
import * as a_create_design_system from "../actions/create-design-system";
import * as a_create_design from "../actions/create-design";
import * as a_create_file from "../actions/create-file";
import * as a_create_fusion_app from "../actions/create-fusion-app";
import * as a_delete_design_state from "../actions/delete-design-state";
import * as a_delete_design_system from "../actions/delete-design-system";
import * as a_delete_design_template from "../actions/delete-design-template";
import * as a_delete_design from "../actions/delete-design";
import * as a_delete_file from "../actions/delete-file";
import * as a_delete_staged_dataset from "../actions/delete-staged-dataset";
import * as a_deploy_design_preview from "../actions/deploy-design-preview";
import * as a_deploy_fusion_app from "../actions/deploy-fusion-app";
import * as a_detach_component_instance from "../actions/detach-component-instance";
import * as a_duplicate_design from "../actions/duplicate-design";
import * as a_edit_design from "../actions/edit-design";
import * as a_export_coding_handoff from "../actions/export-coding-handoff";
import * as a_export_design_as_figma_svg from "../actions/export-design-as-figma-svg";
import * as a_export_html from "../actions/export-html";
import * as a_export_pdf from "../actions/export-pdf";
import * as a_export_svg from "../actions/export-svg";
import * as a_export_zip from "../actions/export-zip";
import * as a_generate_design_title from "../actions/generate-design-title";
import * as a_generate_design from "../actions/generate-design";
import * as a_generate_screens from "../actions/generate-screens";
import * as a_get_code_layer_projection from "../actions/get-code-layer-projection";
import * as a_get_component_details from "../actions/get-component-details";
import * as a_get_design_branch_diff from "../actions/get-design-branch-diff";
import * as a_get_design_review from "../actions/get-design-review";
import * as a_get_design_snapshot from "../actions/get-design-snapshot";
import * as a_get_design_surface_index from "../actions/get-design-surface-index";
import * as a_get_design_system from "../actions/get-design-system";
import * as a_get_design_template from "../actions/get-design-template";
import * as a_get_design from "../actions/get-design";
import * as a_get_figma_connection_status from "../actions/get-figma-connection-status";
import * as a_get_figma_design_context from "../actions/get-figma-design-context";
import * as a_get_figma_styles from "../actions/get-figma-styles";
import * as a_get_fusion_deploy_status from "../actions/get-fusion-deploy-status";
import * as a_get_motion_timeline from "../actions/get-motion-timeline";
import * as a_get_shader from "../actions/get-shader";
import * as a_go_to_main_component from "../actions/go-to-main-component";
import * as a_grant_localhost_write_consent from "../actions/grant-localhost-write-consent";
import * as a_hydrate_figma_paste_images from "../actions/hydrate-figma-paste-images";
import * as a_import_code from "../actions/import-code";
import * as a_import_design_project from "../actions/import-design-project";
import * as a_import_design_source from "../actions/import-design-source";
import * as a_import_design_tokens from "../actions/import-design-tokens";
import * as a_import_document from "../actions/import-document";
import * as a_import_figma_clipboard from "../actions/import-figma-clipboard";
import * as a_import_figma_frame from "../actions/import-figma-frame";
import * as a_import_from_url from "../actions/import-from-url";
import * as a_import_github from "../actions/import-github";
import * as a_index_components from "../actions/index-components";
import * as a_index_design_system_with_builder from "../actions/index-design-system-with-builder";
import * as a_index_design_tokens from "../actions/index-design-tokens";
import * as a_insert_asset from "../actions/insert-asset";
import * as a_insert_design_native_asset from "../actions/insert-design-native-asset";
import * as a_insert_figma_library_asset from "../actions/insert-figma-library-asset";
import * as a_list_design_components from "../actions/list-design-components";
import * as a_list_design_extensions from "../actions/list-design-extensions";
import * as a_list_design_native_assets from "../actions/list-design-native-assets";
import * as a_list_design_source_capabilities from "../actions/list-design-source-capabilities";
import * as a_list_design_states from "../actions/list-design-states";
import * as a_list_design_systems from "../actions/list-design-systems";
import * as a_list_design_templates from "../actions/list-design-templates";
import * as a_list_designs from "../actions/list-designs";
import * as a_list_figma_library_assets from "../actions/list-figma-library-assets";
import * as a_list_files from "../actions/list-files";
import * as a_list_fusion_edits from "../actions/list-fusion-edits";
import * as a_list_local_files from "../actions/list-local-files";
import * as a_list_localhost_connections from "../actions/list-localhost-connections";
import * as a_list_source_files from "../actions/list-source-files";
import * as a_list_staged_datasets from "../actions/list-staged-datasets";
import * as a_migrate_board_objects_to_file from "../actions/migrate-board-objects-to-file";
import * as a_migrate_inline_design_to_app from "../actions/migrate-inline-design-to-app";
import * as a_navigate from "../actions/navigate";
import * as a_open_component_source from "../actions/open-component-source";
import * as a_open_visual_edit from "../actions/open-visual-edit";
import * as a_present_design_variants from "../actions/present-design-variants";
import * as a_preview_component_prop_edit from "../actions/preview-component-prop-edit";
import * as a_preview_design_token_edit from "../actions/preview-design-token-edit";
import * as a_preview_shader_fill from "../actions/preview-shader-fill";
import * as a_preview_source_edit from "../actions/preview-source-edit";
import * as a_propose_node_rewrite from "../actions/propose-node-rewrite";
import * as a_provider_api_catalog from "../actions/provider-api-catalog";
import * as a_provider_api_docs from "../actions/provider-api-docs";
import * as a_provider_api_request from "../actions/provider-api-request";
import * as a_push_fusion_app from "../actions/push-fusion-app";
import * as a_query_staged_dataset from "../actions/query-staged-dataset";
import * as a_queue_fusion_edit from "../actions/queue-fusion-edit";
import * as a_read_local_file from "../actions/read-local-file";
import * as a_read_source_file from "../actions/read-source-file";
import * as a_refresh_design_system_with_builder from "../actions/refresh-design-system-with-builder";
import * as a_remove_breakpoint from "../actions/remove-breakpoint";
import * as a_remove_motion_timeline from "../actions/remove-motion-timeline";
import * as a_rename_screen from "../actions/rename-screen";
import * as a_request_localhost_write_consent from "../actions/request-localhost-write-consent";
import * as a_resolve_node_rewrite from "../actions/resolve-node-rewrite";
import * as a_resolve_selection_source from "../actions/resolve-selection-source";
import * as a_revoke_localhost_write_consent from "../actions/revoke-localhost-write-consent";
import * as a_run_design_audit from "../actions/run-design-audit";
import * as a_run_design_extension_action from "../actions/run-design-extension-action";
import * as a_save_design_as_template from "../actions/save-design-as-template";
import * as a_send_fusion_message from "../actions/send-fusion-message";
import * as a_set_active_breakpoint from "../actions/set-active-breakpoint";
import * as a_set_default_design_system from "../actions/set-default-design-system";
import * as a_show_design_questions from "../actions/show-design-questions";
import * as a_swap_component_instance from "../actions/swap-component-instance";
import * as a_sync_design_system_with_builder from "../actions/sync-design-system-with-builder";
import * as a_sync_fusion_app from "../actions/sync-fusion-app";
import * as a_take_design_screenshot from "../actions/take-design-screenshot";
import * as a_update_design_system from "../actions/update-design-system";
import * as a_update_design from "../actions/update-design";
import * as a_update_file from "../actions/update-file";
import * as a_view_screen from "../actions/view-screen";
import * as a_write_local_file from "../actions/write-local-file";
import * as a_get_feature_flags from "@agent-native/core/feature-flags/actions/get-feature-flags";
import * as a_list_feature_flags from "@agent-native/core/feature-flags/actions/list-feature-flags";
import * as a_set_feature_flag from "@agent-native/core/feature-flags/actions/set-feature-flag";
import * as a_get_hosted_harness_config from "@agent-native/core/hosted-harness/actions/get-hosted-harness-config";
import * as a_set_hosted_harness_enabled from "@agent-native/core/hosted-harness/actions/set-hosted-harness-enabled";
import * as a_set_tool_approval_policy from "@agent-native/core/agent/actions/set-tool-approval-policy";
import * as a_share_resource from "@agent-native/core/sharing/actions/share-resource";
import * as a_unshare_resource from "@agent-native/core/sharing/actions/unshare-resource";
import * as a_list_resource_shares from "@agent-native/core/sharing/actions/list-resource-shares";
import * as a_set_resource_visibility from "@agent-native/core/sharing/actions/set-resource-visibility";
import * as a_upload_image from "@agent-native/core/file-upload/actions/upload-image";
import * as a_list_workspace_user_groups from "@agent-native/core/workspace-connections/actions/list-workspace-user-groups";
import * as a_upsert_workspace_user_group from "@agent-native/core/workspace-connections/actions/upsert-workspace-user-group";
import * as a_bulk_update_workspace_user_groups from "@agent-native/core/workspace-connections/actions/bulk-update-workspace-user-groups";
import * as a_delete_workspace_user_group from "@agent-native/core/workspace-connections/actions/delete-workspace-user-group";
import * as a_context_manifest_get from "@agent-native/core/agent/context-xray/actions/context-manifest-get";
import * as a_context_pin from "@agent-native/core/agent/context-xray/actions/context-pin";
import * as a_context_evict from "@agent-native/core/agent/context-xray/actions/context-evict";
import * as a_context_restore from "@agent-native/core/agent/context-xray/actions/context-restore";
import * as a_context_report from "@agent-native/core/agent/context-xray/actions/context-report";
import * as a_get_localization_preference from "@agent-native/core/localization/actions/get-localization-preference";
import * as a_set_localization_preference from "@agent-native/core/localization/actions/set-localization-preference";
import * as a_get_usage_alerts from "@agent-native/core/usage/actions/get-usage-alerts";
import * as a_manage_usage_alert from "@agent-native/core/usage/actions/manage-usage-alert";
import * as a_get_usage_metrics from "@agent-native/core/usage/actions/get-usage-metrics";
import * as a_create_resource_version from "@agent-native/core/history/actions/create-resource-version";
import * as a_list_resource_versions from "@agent-native/core/history/actions/list-resource-versions";
import * as a_get_resource_version from "@agent-native/core/history/actions/get-resource-version";
import * as a_restore_resource_version from "@agent-native/core/history/actions/restore-resource-version";
import * as a_list_resource_history from "@agent-native/core/history/actions/list-resource-history";
import * as a_list_review_comments from "@agent-native/core/review/actions/list-review-comments";
import * as a_create_review_comment from "@agent-native/core/review/actions/create-review-comment";
import * as a_reply_review_comment from "@agent-native/core/review/actions/reply-review-comment";
import * as a_resolve_review_thread from "@agent-native/core/review/actions/resolve-review-thread";
import * as a_delete_review_comment from "@agent-native/core/review/actions/delete-review-comment";
import * as a_consume_review_feedback from "@agent-native/core/review/actions/consume-review-feedback";
import * as a_get_review_feedback from "@agent-native/core/review/actions/get-review-feedback";
import * as a_set_review_status from "@agent-native/core/review/actions/set-review-status";
import * as a_send_review_thread_to_agent from "@agent-native/core/review/actions/send-review-thread-to-agent";

const modules: Record<string, unknown> = {
  "add-breakpoint": a_add_breakpoint,
  "add-fusion-screens": a_add_fusion_screens,
  "add-localhost-screens": a_add_localhost_screens,
  "analyze-brand-assets": a_analyze_brand_assets,
  "apply-a11y-fix": a_apply_a11y_fix,
  "apply-component-prop-edit": a_apply_component_prop_edit,
  "apply-design-state": a_apply_design_state,
  "apply-design-token-edit": a_apply_design_token_edit,
  "apply-fusion-edits": a_apply_fusion_edits,
  "apply-motion-edit": a_apply_motion_edit,
  "apply-shader-fill": a_apply_shader_fill,
  "apply-shader": a_apply_shader,
  "apply-source-edit": a_apply_source_edit,
  "apply-tweaks": a_apply_tweaks,
  "apply-visual-edit": a_apply_visual_edit,
  "begin-node-rewrite-request": a_begin_node_rewrite_request,
  "cancel-node-rewrite-request": a_cancel_node_rewrite_request,
  "capture-design-state": a_capture_design_state,
  "clone-creative-context-design-native": a_clone_creative_context_design_native,
  "clone-creative-context-design": a_clone_creative_context_design,
  "connect-assets-mcp": a_connect_assets_mcp,
  "connect-builder-app": a_connect_builder_app,
  "connect-localhost": a_connect_localhost,
  "create-component": a_create_component,
  "create-design-branch": a_create_design_branch,
  "create-design-from-template": a_create_design_from_template,
  "create-design-state": a_create_design_state,
  "create-design-system": a_create_design_system,
  "create-design": a_create_design,
  "create-file": a_create_file,
  "create-fusion-app": a_create_fusion_app,
  "delete-design-state": a_delete_design_state,
  "delete-design-system": a_delete_design_system,
  "delete-design-template": a_delete_design_template,
  "delete-design": a_delete_design,
  "delete-file": a_delete_file,
  "delete-staged-dataset": a_delete_staged_dataset,
  "deploy-design-preview": a_deploy_design_preview,
  "deploy-fusion-app": a_deploy_fusion_app,
  "detach-component-instance": a_detach_component_instance,
  "duplicate-design": a_duplicate_design,
  "edit-design": a_edit_design,
  "export-coding-handoff": a_export_coding_handoff,
  "export-design-as-figma-svg": a_export_design_as_figma_svg,
  "export-html": a_export_html,
  "export-pdf": a_export_pdf,
  "export-svg": a_export_svg,
  "export-zip": a_export_zip,
  "generate-design-title": a_generate_design_title,
  "generate-design": a_generate_design,
  "generate-screens": a_generate_screens,
  "get-code-layer-projection": a_get_code_layer_projection,
  "get-component-details": a_get_component_details,
  "get-design-branch-diff": a_get_design_branch_diff,
  "get-design-review": a_get_design_review,
  "get-design-snapshot": a_get_design_snapshot,
  "get-design-surface-index": a_get_design_surface_index,
  "get-design-system": a_get_design_system,
  "get-design-template": a_get_design_template,
  "get-design": a_get_design,
  "get-figma-connection-status": a_get_figma_connection_status,
  "get-figma-design-context": a_get_figma_design_context,
  "get-figma-styles": a_get_figma_styles,
  "get-fusion-deploy-status": a_get_fusion_deploy_status,
  "get-motion-timeline": a_get_motion_timeline,
  "get-shader": a_get_shader,
  "go-to-main-component": a_go_to_main_component,
  "grant-localhost-write-consent": a_grant_localhost_write_consent,
  "hydrate-figma-paste-images": a_hydrate_figma_paste_images,
  "import-code": a_import_code,
  "import-design-project": a_import_design_project,
  "import-design-source": a_import_design_source,
  "import-design-tokens": a_import_design_tokens,
  "import-document": a_import_document,
  "import-figma-clipboard": a_import_figma_clipboard,
  "import-figma-frame": a_import_figma_frame,
  "import-from-url": a_import_from_url,
  "import-github": a_import_github,
  "index-components": a_index_components,
  "index-design-system-with-builder": a_index_design_system_with_builder,
  "index-design-tokens": a_index_design_tokens,
  "insert-asset": a_insert_asset,
  "insert-design-native-asset": a_insert_design_native_asset,
  "insert-figma-library-asset": a_insert_figma_library_asset,
  "list-design-components": a_list_design_components,
  "list-design-extensions": a_list_design_extensions,
  "list-design-native-assets": a_list_design_native_assets,
  "list-design-source-capabilities": a_list_design_source_capabilities,
  "list-design-states": a_list_design_states,
  "list-design-systems": a_list_design_systems,
  "list-design-templates": a_list_design_templates,
  "list-designs": a_list_designs,
  "list-figma-library-assets": a_list_figma_library_assets,
  "list-files": a_list_files,
  "list-fusion-edits": a_list_fusion_edits,
  "list-local-files": a_list_local_files,
  "list-localhost-connections": a_list_localhost_connections,
  "list-source-files": a_list_source_files,
  "list-staged-datasets": a_list_staged_datasets,
  "migrate-board-objects-to-file": a_migrate_board_objects_to_file,
  "migrate-inline-design-to-app": a_migrate_inline_design_to_app,
  "navigate": a_navigate,
  "open-component-source": a_open_component_source,
  "open-visual-edit": a_open_visual_edit,
  "present-design-variants": a_present_design_variants,
  "preview-component-prop-edit": a_preview_component_prop_edit,
  "preview-design-token-edit": a_preview_design_token_edit,
  "preview-shader-fill": a_preview_shader_fill,
  "preview-source-edit": a_preview_source_edit,
  "propose-node-rewrite": a_propose_node_rewrite,
  "provider-api-catalog": a_provider_api_catalog,
  "provider-api-docs": a_provider_api_docs,
  "provider-api-request": a_provider_api_request,
  "push-fusion-app": a_push_fusion_app,
  "query-staged-dataset": a_query_staged_dataset,
  "queue-fusion-edit": a_queue_fusion_edit,
  "read-local-file": a_read_local_file,
  "read-source-file": a_read_source_file,
  "refresh-design-system-with-builder": a_refresh_design_system_with_builder,
  "remove-breakpoint": a_remove_breakpoint,
  "remove-motion-timeline": a_remove_motion_timeline,
  "rename-screen": a_rename_screen,
  "request-localhost-write-consent": a_request_localhost_write_consent,
  "resolve-node-rewrite": a_resolve_node_rewrite,
  "resolve-selection-source": a_resolve_selection_source,
  "revoke-localhost-write-consent": a_revoke_localhost_write_consent,
  "run-design-audit": a_run_design_audit,
  "run-design-extension-action": a_run_design_extension_action,
  "save-design-as-template": a_save_design_as_template,
  "send-fusion-message": a_send_fusion_message,
  "set-active-breakpoint": a_set_active_breakpoint,
  "set-default-design-system": a_set_default_design_system,
  "show-design-questions": a_show_design_questions,
  "swap-component-instance": a_swap_component_instance,
  "sync-design-system-with-builder": a_sync_design_system_with_builder,
  "sync-fusion-app": a_sync_fusion_app,
  "take-design-screenshot": a_take_design_screenshot,
  "update-design-system": a_update_design_system,
  "update-design": a_update_design,
  "update-file": a_update_file,
  "view-screen": a_view_screen,
  "write-local-file": a_write_local_file,
  "get-feature-flags": a_get_feature_flags,
  "list-feature-flags": a_list_feature_flags,
  "set-feature-flag": a_set_feature_flag,
  "get-hosted-harness-config": a_get_hosted_harness_config,
  "set-hosted-harness-enabled": a_set_hosted_harness_enabled,
  "set-tool-approval-policy": a_set_tool_approval_policy,
  "share-resource": a_share_resource,
  "unshare-resource": a_unshare_resource,
  "list-resource-shares": a_list_resource_shares,
  "set-resource-visibility": a_set_resource_visibility,
  "upload-image": a_upload_image,
  "list-workspace-user-groups": a_list_workspace_user_groups,
  "upsert-workspace-user-group": a_upsert_workspace_user_group,
  "bulk-update-workspace-user-groups": a_bulk_update_workspace_user_groups,
  "delete-workspace-user-group": a_delete_workspace_user_group,
  "context-manifest-get": a_context_manifest_get,
  "context-pin": a_context_pin,
  "context-evict": a_context_evict,
  "context-restore": a_context_restore,
  "context-report": a_context_report,
  "get-localization-preference": a_get_localization_preference,
  "set-localization-preference": a_set_localization_preference,
  "get-usage-alerts": a_get_usage_alerts,
  "manage-usage-alert": a_manage_usage_alert,
  "get-usage-metrics": a_get_usage_metrics,
  "create-resource-version": a_create_resource_version,
  "list-resource-versions": a_list_resource_versions,
  "get-resource-version": a_get_resource_version,
  "restore-resource-version": a_restore_resource_version,
  "list-resource-history": a_list_resource_history,
  "list-review-comments": a_list_review_comments,
  "create-review-comment": a_create_review_comment,
  "reply-review-comment": a_reply_review_comment,
  "resolve-review-thread": a_resolve_review_thread,
  "delete-review-comment": a_delete_review_comment,
  "consume-review-feedback": a_consume_review_feedback,
  "get-review-feedback": a_get_review_feedback,
  "set-review-status": a_set_review_status,
  "send-review-thread-to-agent": a_send_review_thread_to_agent,
};

export default modules;
