// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Regenerated when files in actions/ change.
// This file augments the ActionRegistry interface so that useActionQuery and
// useActionMutation infer the correct types from your action definitions.

/** Extract the return type and parameter type from a defineAction module. */
type ActionEntry<T> = T extends { default: { run: (...args: infer A) => infer R } }
  ? {
      result: Awaited<R>;
      params: A extends [infer P, ...any[]] ? P : Record<string, any>;
    }
  : { result: any; params: Record<string, any> };

declare global {
  interface AgentNativeActionRegistry {
    "add-breakpoint": ActionEntry<typeof import("../actions/add-breakpoint")>;
    "add-fusion-screens": ActionEntry<typeof import("../actions/add-fusion-screens")>;
    "add-localhost-screens": ActionEntry<typeof import("../actions/add-localhost-screens")>;
    "analyze-brand-assets": ActionEntry<typeof import("../actions/analyze-brand-assets")>;
    "apply-a11y-fix": ActionEntry<typeof import("../actions/apply-a11y-fix")>;
    "apply-component-prop-edit": ActionEntry<typeof import("../actions/apply-component-prop-edit")>;
    "apply-design-state": ActionEntry<typeof import("../actions/apply-design-state")>;
    "apply-design-token-edit": ActionEntry<typeof import("../actions/apply-design-token-edit")>;
    "apply-fusion-edits": ActionEntry<typeof import("../actions/apply-fusion-edits")>;
    "apply-motion-edit": ActionEntry<typeof import("../actions/apply-motion-edit")>;
    "apply-shader-fill": ActionEntry<typeof import("../actions/apply-shader-fill")>;
    "apply-shader": ActionEntry<typeof import("../actions/apply-shader")>;
    "apply-source-edit": ActionEntry<typeof import("../actions/apply-source-edit")>;
    "apply-tweaks": ActionEntry<typeof import("../actions/apply-tweaks")>;
    "apply-visual-edit": ActionEntry<typeof import("../actions/apply-visual-edit")>;
    "begin-node-rewrite-request": ActionEntry<typeof import("../actions/begin-node-rewrite-request")>;
    "cancel-node-rewrite-request": ActionEntry<typeof import("../actions/cancel-node-rewrite-request")>;
    "capture-design-state": ActionEntry<typeof import("../actions/capture-design-state")>;
    "clone-creative-context-design-native": ActionEntry<typeof import("../actions/clone-creative-context-design-native")>;
    "clone-creative-context-design": ActionEntry<typeof import("../actions/clone-creative-context-design")>;
    "connect-assets-mcp": ActionEntry<typeof import("../actions/connect-assets-mcp")>;
    "connect-builder-app": ActionEntry<typeof import("../actions/connect-builder-app")>;
    "connect-localhost": ActionEntry<typeof import("../actions/connect-localhost")>;
    "create-component": ActionEntry<typeof import("../actions/create-component")>;
    "create-design-branch": ActionEntry<typeof import("../actions/create-design-branch")>;
    "create-design-from-template": ActionEntry<typeof import("../actions/create-design-from-template")>;
    "create-design-state": ActionEntry<typeof import("../actions/create-design-state")>;
    "create-design-system": ActionEntry<typeof import("../actions/create-design-system")>;
    "create-design": ActionEntry<typeof import("../actions/create-design")>;
    "create-file": ActionEntry<typeof import("../actions/create-file")>;
    "create-fusion-app": ActionEntry<typeof import("../actions/create-fusion-app")>;
    "delete-design-state": ActionEntry<typeof import("../actions/delete-design-state")>;
    "delete-design-system": ActionEntry<typeof import("../actions/delete-design-system")>;
    "delete-design-template": ActionEntry<typeof import("../actions/delete-design-template")>;
    "delete-design": ActionEntry<typeof import("../actions/delete-design")>;
    "delete-file": ActionEntry<typeof import("../actions/delete-file")>;
    "delete-staged-dataset": ActionEntry<typeof import("../actions/delete-staged-dataset")>;
    "deploy-design-preview": ActionEntry<typeof import("../actions/deploy-design-preview")>;
    "deploy-fusion-app": ActionEntry<typeof import("../actions/deploy-fusion-app")>;
    "detach-component-instance": ActionEntry<typeof import("../actions/detach-component-instance")>;
    "duplicate-design": ActionEntry<typeof import("../actions/duplicate-design")>;
    "edit-design": ActionEntry<typeof import("../actions/edit-design")>;
    "export-coding-handoff": ActionEntry<typeof import("../actions/export-coding-handoff")>;
    "export-design-as-figma-svg": ActionEntry<typeof import("../actions/export-design-as-figma-svg")>;
    "export-html": ActionEntry<typeof import("../actions/export-html")>;
    "export-pdf": ActionEntry<typeof import("../actions/export-pdf")>;
    "export-svg": ActionEntry<typeof import("../actions/export-svg")>;
    "export-zip": ActionEntry<typeof import("../actions/export-zip")>;
    "generate-design-title": ActionEntry<typeof import("../actions/generate-design-title")>;
    "generate-design": ActionEntry<typeof import("../actions/generate-design")>;
    "generate-screens": ActionEntry<typeof import("../actions/generate-screens")>;
    "get-code-layer-projection": ActionEntry<typeof import("../actions/get-code-layer-projection")>;
    "get-component-details": ActionEntry<typeof import("../actions/get-component-details")>;
    "get-design-branch-diff": ActionEntry<typeof import("../actions/get-design-branch-diff")>;
    "get-design-review": ActionEntry<typeof import("../actions/get-design-review")>;
    "get-design-snapshot": ActionEntry<typeof import("../actions/get-design-snapshot")>;
    "get-design-surface-index": ActionEntry<typeof import("../actions/get-design-surface-index")>;
    "get-design-system": ActionEntry<typeof import("../actions/get-design-system")>;
    "get-design-template": ActionEntry<typeof import("../actions/get-design-template")>;
    "get-design": ActionEntry<typeof import("../actions/get-design")>;
    "get-figma-connection-status": ActionEntry<typeof import("../actions/get-figma-connection-status")>;
    "get-figma-design-context": ActionEntry<typeof import("../actions/get-figma-design-context")>;
    "get-figma-styles": ActionEntry<typeof import("../actions/get-figma-styles")>;
    "get-fusion-deploy-status": ActionEntry<typeof import("../actions/get-fusion-deploy-status")>;
    "get-motion-timeline": ActionEntry<typeof import("../actions/get-motion-timeline")>;
    "get-shader": ActionEntry<typeof import("../actions/get-shader")>;
    "go-to-main-component": ActionEntry<typeof import("../actions/go-to-main-component")>;
    "grant-localhost-write-consent": ActionEntry<typeof import("../actions/grant-localhost-write-consent")>;
    "hydrate-figma-paste-images": ActionEntry<typeof import("../actions/hydrate-figma-paste-images")>;
    "import-code": ActionEntry<typeof import("../actions/import-code")>;
    "import-design-project": ActionEntry<typeof import("../actions/import-design-project")>;
    "import-design-source": ActionEntry<typeof import("../actions/import-design-source")>;
    "import-design-tokens": ActionEntry<typeof import("../actions/import-design-tokens")>;
    "import-document": ActionEntry<typeof import("../actions/import-document")>;
    "import-figma-clipboard": ActionEntry<typeof import("../actions/import-figma-clipboard")>;
    "import-figma-frame": ActionEntry<typeof import("../actions/import-figma-frame")>;
    "import-from-url": ActionEntry<typeof import("../actions/import-from-url")>;
    "import-github": ActionEntry<typeof import("../actions/import-github")>;
    "index-components": ActionEntry<typeof import("../actions/index-components")>;
    "index-design-system-with-builder": ActionEntry<typeof import("../actions/index-design-system-with-builder")>;
    "index-design-tokens": ActionEntry<typeof import("../actions/index-design-tokens")>;
    "insert-asset": ActionEntry<typeof import("../actions/insert-asset")>;
    "insert-design-native-asset": ActionEntry<typeof import("../actions/insert-design-native-asset")>;
    "insert-figma-library-asset": ActionEntry<typeof import("../actions/insert-figma-library-asset")>;
    "list-design-components": ActionEntry<typeof import("../actions/list-design-components")>;
    "list-design-extensions": ActionEntry<typeof import("../actions/list-design-extensions")>;
    "list-design-native-assets": ActionEntry<typeof import("../actions/list-design-native-assets")>;
    "list-design-source-capabilities": ActionEntry<typeof import("../actions/list-design-source-capabilities")>;
    "list-design-states": ActionEntry<typeof import("../actions/list-design-states")>;
    "list-design-systems": ActionEntry<typeof import("../actions/list-design-systems")>;
    "list-design-templates": ActionEntry<typeof import("../actions/list-design-templates")>;
    "list-designs": ActionEntry<typeof import("../actions/list-designs")>;
    "list-figma-library-assets": ActionEntry<typeof import("../actions/list-figma-library-assets")>;
    "list-files": ActionEntry<typeof import("../actions/list-files")>;
    "list-fusion-edits": ActionEntry<typeof import("../actions/list-fusion-edits")>;
    "list-local-files": ActionEntry<typeof import("../actions/list-local-files")>;
    "list-localhost-connections": ActionEntry<typeof import("../actions/list-localhost-connections")>;
    "list-source-files": ActionEntry<typeof import("../actions/list-source-files")>;
    "list-staged-datasets": ActionEntry<typeof import("../actions/list-staged-datasets")>;
    "migrate-board-objects-to-file": ActionEntry<typeof import("../actions/migrate-board-objects-to-file")>;
    "migrate-inline-design-to-app": ActionEntry<typeof import("../actions/migrate-inline-design-to-app")>;
    "navigate": ActionEntry<typeof import("../actions/navigate")>;
    "open-component-source": ActionEntry<typeof import("../actions/open-component-source")>;
    "open-visual-edit": ActionEntry<typeof import("../actions/open-visual-edit")>;
    "present-design-variants": ActionEntry<typeof import("../actions/present-design-variants")>;
    "preview-component-prop-edit": ActionEntry<typeof import("../actions/preview-component-prop-edit")>;
    "preview-design-token-edit": ActionEntry<typeof import("../actions/preview-design-token-edit")>;
    "preview-shader-fill": ActionEntry<typeof import("../actions/preview-shader-fill")>;
    "preview-source-edit": ActionEntry<typeof import("../actions/preview-source-edit")>;
    "propose-node-rewrite": ActionEntry<typeof import("../actions/propose-node-rewrite")>;
    "provider-api-catalog": ActionEntry<typeof import("../actions/provider-api-catalog")>;
    "provider-api-docs": ActionEntry<typeof import("../actions/provider-api-docs")>;
    "provider-api-request": ActionEntry<typeof import("../actions/provider-api-request")>;
    "push-fusion-app": ActionEntry<typeof import("../actions/push-fusion-app")>;
    "query-staged-dataset": ActionEntry<typeof import("../actions/query-staged-dataset")>;
    "queue-fusion-edit": ActionEntry<typeof import("../actions/queue-fusion-edit")>;
    "read-local-file": ActionEntry<typeof import("../actions/read-local-file")>;
    "read-source-file": ActionEntry<typeof import("../actions/read-source-file")>;
    "refresh-design-system-with-builder": ActionEntry<typeof import("../actions/refresh-design-system-with-builder")>;
    "remove-breakpoint": ActionEntry<typeof import("../actions/remove-breakpoint")>;
    "remove-motion-timeline": ActionEntry<typeof import("../actions/remove-motion-timeline")>;
    "rename-screen": ActionEntry<typeof import("../actions/rename-screen")>;
    "request-localhost-write-consent": ActionEntry<typeof import("../actions/request-localhost-write-consent")>;
    "resolve-node-rewrite": ActionEntry<typeof import("../actions/resolve-node-rewrite")>;
    "resolve-selection-source": ActionEntry<typeof import("../actions/resolve-selection-source")>;
    "revoke-localhost-write-consent": ActionEntry<typeof import("../actions/revoke-localhost-write-consent")>;
    "run-design-audit": ActionEntry<typeof import("../actions/run-design-audit")>;
    "run-design-extension-action": ActionEntry<typeof import("../actions/run-design-extension-action")>;
    "save-design-as-template": ActionEntry<typeof import("../actions/save-design-as-template")>;
    "send-fusion-message": ActionEntry<typeof import("../actions/send-fusion-message")>;
    "set-active-breakpoint": ActionEntry<typeof import("../actions/set-active-breakpoint")>;
    "set-default-design-system": ActionEntry<typeof import("../actions/set-default-design-system")>;
    "show-design-questions": ActionEntry<typeof import("../actions/show-design-questions")>;
    "swap-component-instance": ActionEntry<typeof import("../actions/swap-component-instance")>;
    "sync-design-system-with-builder": ActionEntry<typeof import("../actions/sync-design-system-with-builder")>;
    "sync-fusion-app": ActionEntry<typeof import("../actions/sync-fusion-app")>;
    "take-design-screenshot": ActionEntry<typeof import("../actions/take-design-screenshot")>;
    "update-design-system": ActionEntry<typeof import("../actions/update-design-system")>;
    "update-design": ActionEntry<typeof import("../actions/update-design")>;
    "update-file": ActionEntry<typeof import("../actions/update-file")>;
    "view-screen": ActionEntry<typeof import("../actions/view-screen")>;
    "write-local-file": ActionEntry<typeof import("../actions/write-local-file")>;
    "get-feature-flags": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/get-feature-flags")>;
    "list-feature-flags": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/list-feature-flags")>;
    "set-feature-flag": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/set-feature-flag")>;
    "get-hosted-harness-config": ActionEntry<typeof import("@agent-native/core/hosted-harness/actions/get-hosted-harness-config")>;
    "set-hosted-harness-enabled": ActionEntry<typeof import("@agent-native/core/hosted-harness/actions/set-hosted-harness-enabled")>;
    "set-tool-approval-policy": ActionEntry<typeof import("@agent-native/core/agent/actions/set-tool-approval-policy")>;
    "share-resource": ActionEntry<typeof import("@agent-native/core/sharing/actions/share-resource")>;
    "unshare-resource": ActionEntry<typeof import("@agent-native/core/sharing/actions/unshare-resource")>;
    "list-resource-shares": ActionEntry<typeof import("@agent-native/core/sharing/actions/list-resource-shares")>;
    "set-resource-visibility": ActionEntry<typeof import("@agent-native/core/sharing/actions/set-resource-visibility")>;
    "upload-image": ActionEntry<typeof import("@agent-native/core/file-upload/actions/upload-image")>;
    "list-workspace-user-groups": ActionEntry<typeof import("@agent-native/core/workspace-connections/actions/list-workspace-user-groups")>;
    "upsert-workspace-user-group": ActionEntry<typeof import("@agent-native/core/workspace-connections/actions/upsert-workspace-user-group")>;
    "bulk-update-workspace-user-groups": ActionEntry<typeof import("@agent-native/core/workspace-connections/actions/bulk-update-workspace-user-groups")>;
    "delete-workspace-user-group": ActionEntry<typeof import("@agent-native/core/workspace-connections/actions/delete-workspace-user-group")>;
    "context-manifest-get": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-manifest-get")>;
    "context-pin": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-pin")>;
    "context-evict": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-evict")>;
    "context-restore": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-restore")>;
    "context-report": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-report")>;
    "get-localization-preference": ActionEntry<typeof import("@agent-native/core/localization/actions/get-localization-preference")>;
    "set-localization-preference": ActionEntry<typeof import("@agent-native/core/localization/actions/set-localization-preference")>;
    "get-usage-alerts": ActionEntry<typeof import("@agent-native/core/usage/actions/get-usage-alerts")>;
    "manage-usage-alert": ActionEntry<typeof import("@agent-native/core/usage/actions/manage-usage-alert")>;
    "get-usage-metrics": ActionEntry<typeof import("@agent-native/core/usage/actions/get-usage-metrics")>;
    "create-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/create-resource-version")>;
    "list-resource-versions": ActionEntry<typeof import("@agent-native/core/history/actions/list-resource-versions")>;
    "get-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/get-resource-version")>;
    "restore-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/restore-resource-version")>;
    "list-resource-history": ActionEntry<typeof import("@agent-native/core/history/actions/list-resource-history")>;
    "list-review-comments": ActionEntry<typeof import("@agent-native/core/review/actions/list-review-comments")>;
    "create-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/create-review-comment")>;
    "reply-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/reply-review-comment")>;
    "resolve-review-thread": ActionEntry<typeof import("@agent-native/core/review/actions/resolve-review-thread")>;
    "delete-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/delete-review-comment")>;
    "consume-review-feedback": ActionEntry<typeof import("@agent-native/core/review/actions/consume-review-feedback")>;
    "get-review-feedback": ActionEntry<typeof import("@agent-native/core/review/actions/get-review-feedback")>;
    "set-review-status": ActionEntry<typeof import("@agent-native/core/review/actions/set-review-status")>;
    "send-review-thread-to-agent": ActionEntry<typeof import("@agent-native/core/review/actions/send-review-thread-to-agent")>;
  }
}

declare module "@agent-native/core/client" {
  interface ActionRegistry extends AgentNativeActionRegistry {}
}

declare module "@agent-native/core/client/hooks" {
  interface ActionRegistry extends AgentNativeActionRegistry {}
}

export {};
