import { useResources } from "@agent-native/core/client/resources";
import { useNavigate } from "react-router";

import { ArtifactPreviewPanel } from "@/components/preview/ArtifactPreviewPanel";
import { useArtifactPreview } from "@/components/preview/use-artifact-preview";
import { Button } from "@/components/ui/button";

export function meta() {
  return [{ title: "Artifacts" }];
}

export function HydrateFallback() {
  return (
    <div className="flex h-screen items-center justify-center">
      <div className="size-8 animate-spin rounded-full border-b-2 border-foreground" />
    </div>
  );
}

function formatDate(ms: number) {
  return new Date(ms).toLocaleString("en-US");
}

function formatSize(bytes: number) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

export default function ArtifactsRoute() {
  const artifacts = useResources("workspace");
  const { open } = useArtifactPreview();
  const navigate = useNavigate();

  const htmlArtifacts = (artifacts.data ?? [])
    .filter(
      (r) => r.path?.startsWith("artifacts/") && r.mimeType === "text/html",
    )
    .sort((a, b) => (b.updatedAt ?? 0) - (a.updatedAt ?? 0));

  async function previewArtifact(resourceId: string, path: string) {
    await open({ resourceId, path });
    navigate("/");
  }

  return (
    <div className="mx-auto w-full max-w-3xl p-6">
      <h1 className="mb-1 text-xl font-semibold">Artifacts</h1>
      <p className="mb-6 text-sm text-muted-foreground">
        HTML artifacts generated by the agent. Preview opens beside the chat.
      </p>
      {artifacts.isLoading ? (
        <p className="text-sm text-muted-foreground">Loading…</p>
      ) : htmlArtifacts.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          No artifacts yet. Ask the chat to generate an HTML page.
        </p>
      ) : (
        <ul className="divide-y divide-border rounded-lg border border-border">
          {htmlArtifacts.map((r) => (
            <li key={r.id} className="flex items-center gap-3 px-4 py-3">
              <div className="min-w-0 flex-1">
                <div className="truncate text-sm font-medium">
                  {r.path.replace(/^artifacts\//, "")}
                </div>
                <div className="text-xs text-muted-foreground">
                  {formatSize(r.size ?? 0)} · {formatDate(r.updatedAt ?? 0)}
                </div>
              </div>
              <Button
                type="button"
                size="sm"
                onClick={() => void previewArtifact(r.id, r.path)}
              >
                Preview
              </Button>
            </li>
          ))}
        </ul>
      )}
      <ArtifactPreviewPanel />
    </div>
  );
}
