import { useResources } from "@agent-native/core/client/resources";
import { useEffect, useRef } from "react";
import { useSearchParams } from "react-router";
import { toast } from "sonner";

import { ArtifactPreviewPanel } from "@/components/preview/ArtifactPreviewPanel";
import { selectHtmlArtifacts } from "@/components/preview/artifact-list";
import { useArtifactPreview } from "@/components/preview/use-artifact-preview";
import { Button } from "@/components/ui/button";

export function meta() {
  return [{ title: "Artifacts" }];
}

export function HydrateFallback() {
  return (
    <div className="flex h-screen items-center justify-center">
      <div className="size-8 animate-spin rounded-full border-b-2 border-foreground" />
    </div>
  );
}

function formatDate(ms: number) {
  return new Date(ms).toLocaleString("en-US");
}

function formatSize(bytes: number) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

export default function ArtifactsRoute() {
  const artifacts = useResources("all");
  const { open } = useArtifactPreview();
  const [searchParams, setSearchParams] = useSearchParams();
  const consumedPreviewParam = useRef(false);

  const htmlArtifacts = selectHtmlArtifacts(artifacts.data);

  async function previewArtifact(resourceId: string, path: string) {
    try {
      await open({ resourceId, path, threadId: null });
    } catch {
      toast.error("Couldn't open the preview");
    }
  }

  useEffect(() => {
    if (consumedPreviewParam.current) return;
    if (artifacts.isLoading) return;
    const previewId = searchParams.get("preview");
    if (!previewId) return;

    consumedPreviewParam.current = true;
    const match = htmlArtifacts.find((r) => r.id === previewId);
    if (match) {
      void previewArtifact(match.id, match.path);
    } else {
      toast.error("Artifact not found");
    }
    setSearchParams(
      (prev) => {
        const next = new URLSearchParams(prev);
        next.delete("preview");
        return next;
      },
      { replace: true },
    );
  }, [artifacts.isLoading, htmlArtifacts, searchParams, setSearchParams]);

  return (
    <div className="flex h-full min-h-0">
      <div className="w-[400px] shrink-0 overflow-y-auto p-6">
        <h1 className="mb-1 text-xl font-semibold">Artifacts</h1>
        <p className="mb-6 text-sm text-muted-foreground">
          HTML artifacts generated by the agent.
        </p>
        {artifacts.isLoading ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : htmlArtifacts.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            No artifacts yet. Ask the chat to generate an HTML page.
          </p>
        ) : (
          <ul className="divide-y divide-border rounded-lg border border-border">
            {htmlArtifacts.map((r) => (
              <li key={r.id} className="flex items-center gap-3 px-4 py-3">
                <div className="min-w-0 flex-1">
                  <div className="truncate text-sm font-medium">
                    {r.path.replace(/^artifacts\//, "")}
                  </div>
                  <div className="text-xs text-muted-foreground">
                    {formatSize(r.size ?? 0)} · {formatDate(r.updatedAt ?? 0)}
                  </div>
                </div>
                <Button
                  type="button"
                  size="sm"
                  onClick={() => void previewArtifact(r.id, r.path)}
                >
                  Preview
                </Button>
              </li>
            ))}
          </ul>
        )}
      </div>
      <div className="flex min-w-0 flex-1">
        <ArtifactPreviewPanel scope="page" />
      </div>
    </div>
  );
}
